import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '@douyinfe/semi-ui';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen p-4 bg-slate-400">
        <Button theme="solid" type="primary">
          hello world
        </Button>
      </div>
    </div>
  );
};

export default Home;
