import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '@douyinfe/semi-ui';
import { useDarkMode } from '@hooks/useDarkMode';
import { useMemo } from 'react';

const Home: NextPage = () => {
  const { theme, toggleDarkMode } = useDarkMode();

  const colors = useMemo(
    () => [
      'primary',
      'gray',
      'red',
      'green',
      'yellow',
      'blue',
      'purple',
      'pink',
      'indigo',
    ],
    [],
  );

  const grades = useMemo(
    () => [50, 100, 200, 300, 400, 500, 600, 700, 800, 900],
    [],
  );

  const cubes: string[] = useMemo(
    () =>
      colors.reduce((accu: string[], color) => {
        const group = grades.map((grade) => `bg-${color}-${grade}`);
        return accu.concat(group);
      }, []),
    [colors, grades],
  );

  return (
    <div>
      <Head>
        <title>ElonWu Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen p-4 bg-white dark:bg-black overflow-auto">
        <Button theme="solid" type="primary" onClick={toggleDarkMode}>
          Theme {theme}
        </Button>

        <Button theme="borderless" onClick={toggleDarkMode}>
          Theme {theme}
        </Button>

        <Button theme="solid" type="danger" onClick={toggleDarkMode}>
          Theme {theme}
        </Button>

        <Button theme="solid" type="warning" onClick={toggleDarkMode}>
          Theme {theme}
        </Button>

        {/* <div className="grid grid-cols-10 gap-4 p-4">
          {cubes.map((bg) => (
            <div key={bg} className={`cube ${bg}`} />
          ))}
        </div> */}
        <div className="grid grid-cols-10 gap-4 p-4 items-center">
          <div className={`cube bg-primary-50`} />
          <div className={`cube bg-primary-100`} />
          <div className={`cube bg-primary-200`} />
          <div className={`cube bg-primary-300`} />
          <div className={`cube bg-primary-400`} />
          <div className={`cube bg-primary-500`} />
          <div className={`cube bg-primary-600`} />
          <div className={`cube bg-primary-700`} />
          <div className={`cube bg-primary-800`} />
          <div className={`cube bg-primary-900`} />

          <div className={`cube bg-gray-50`} />
          <div className={`cube bg-gray-100`} />
          <div className={`cube bg-gray-200`} />
          <div className={`cube bg-gray-300`} />
          <div className={`cube bg-gray-400`} />
          <div className={`cube bg-gray-500`} />
          <div className={`cube bg-gray-600`} />
          <div className={`cube bg-gray-700`} />
          <div className={`cube bg-gray-800`} />
          <div className={`cube bg-gray-900`} />

          <div className={`cube bg-red-50`} />
          <div className={`cube bg-red-100`} />
          <div className={`cube bg-red-200`} />
          <div className={`cube bg-red-300`} />
          <div className={`cube bg-red-400`} />
          <div className={`cube bg-red-500`} />
          <div className={`cube bg-red-600`} />
          <div className={`cube bg-red-700`} />
          <div className={`cube bg-red-800`} />
          <div className={`cube bg-red-900`} />

          <div className={`cube bg-green-50`} />
          <div className={`cube bg-green-100`} />
          <div className={`cube bg-green-200`} />
          <div className={`cube bg-green-300`} />
          <div className={`cube bg-green-400`} />
          <div className={`cube bg-green-500`} />
          <div className={`cube bg-green-600`} />
          <div className={`cube bg-green-700`} />
          <div className={`cube bg-green-800`} />
          <div className={`cube bg-green-900`} />

          <div className={`cube bg-yellow-50`} />
          <div className={`cube bg-yellow-100`} />
          <div className={`cube bg-yellow-200`} />
          <div className={`cube bg-yellow-300`} />
          <div className={`cube bg-yellow-400`} />
          <div className={`cube bg-yellow-500`} />
          <div className={`cube bg-yellow-600`} />
          <div className={`cube bg-yellow-700`} />
          <div className={`cube bg-yellow-800`} />
          <div className={`cube bg-yellow-900`} />

          <div className={`cube bg-blue-50`} />
          <div className={`cube bg-blue-100`} />
          <div className={`cube bg-blue-200`} />
          <div className={`cube bg-blue-300`} />
          <div className={`cube bg-blue-400`} />
          <div className={`cube bg-blue-500`} />
          <div className={`cube bg-blue-600`} />
          <div className={`cube bg-blue-700`} />
          <div className={`cube bg-blue-800`} />
          <div className={`cube bg-blue-900`} />

          <div className={`cube bg-purple-50`} />
          <div className={`cube bg-purple-100`} />
          <div className={`cube bg-purple-200`} />
          <div className={`cube bg-purple-300`} />
          <div className={`cube bg-purple-400`} />
          <div className={`cube bg-purple-500`} />
          <div className={`cube bg-purple-600`} />
          <div className={`cube bg-purple-700`} />
          <div className={`cube bg-purple-800`} />
          <div className={`cube bg-purple-900`} />

          <div className={`cube bg-pink-50`} />
          <div className={`cube bg-pink-100`} />
          <div className={`cube bg-pink-200`} />
          <div className={`cube bg-pink-300`} />
          <div className={`cube bg-pink-400`} />
          <div className={`cube bg-pink-500`} />
          <div className={`cube bg-pink-600`} />
          <div className={`cube bg-pink-700`} />
          <div className={`cube bg-pink-800`} />
          <div className={`cube bg-pink-900`} />

          <div className={`cube bg-indigo-50`} />
          <div className={`cube bg-indigo-100`} />
          <div className={`cube bg-indigo-200`} />
          <div className={`cube bg-indigo-300`} />
          <div className={`cube bg-indigo-400`} />
          <div className={`cube bg-indigo-500`} />
          <div className={`cube bg-indigo-600`} />
          <div className={`cube bg-indigo-700`} />
          <div className={`cube bg-indigo-800`} />
          <div className={`cube bg-indigo-900`} />
        </div>
      </div>
    </div>
  );
};

export default Home;
